version: "3"

services:
    db:
        container_name: kickstarter_db
        image: postgres:10.6-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
    web:
        container_name: kickstarter_web
        env_file: .env
        build: .
        command: /src/entrypoint.sh
        volumes:
            - .:/src
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    postgres_data:
